from fpdf import FPDF


class Cheque(FPDF):
    def header(self):
        # Set font and font size
        self.set_font("Arial", "B", 10)

        # Add header text
        self.cell(0, 5, "Cheque", 0, 1, "C")
        self.ln(3)

    def footer(self):
        # Add footer text
        self.set_y(-8)
        self.set_font("Arial", "I", 8)
        self.cell(0, 5, "Generated by YourApp", 0, 0, "C")