# Generated by Django 4.2.1 on 2023-05-12 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed')], default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cafe.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200)),
                ('name_kg', models.CharField(default='Тамак', max_length=200)),
                ('name_ru', models.CharField(default='Еда', max_length=200)),
                ('description_en', models.TextField()),
                ('description_kg', models.TextField(default='Тамак')),
                ('description_ru', models.TextField(default='Еда')),
                ('price', models.FloatField()),
                ('gram', models.IntegerField(default=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.category')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='dishes',
            field=models.ManyToManyField(to='cafe.dish'),
        ),
    ]
