# Generated by Django 4.2.1 on 2023-05-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.table'),
            preserve_default=False,
        ),
    ]
