# Generated by Django 4.2.1 on 2023-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In progress'), (1, 'Completed')], default=0),
        ),
    ]
