# Generated by Django 4.2.1 on 2023-05-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_cart_table_id_alter_cart_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='table_id',
            new_name='table',
        ),
    ]
