# Generated by Django 4.2.1 on 2023-05-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='dishes',
        ),
    ]
