# Generated by Django 4.2.1 on 2023-05-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_remove_cart_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ip_address',
            field=models.CharField(default='ip', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cafe.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.dish'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.category'),
        ),
    ]
