# Generated by Django 4.2.1 on 2023-05-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_cart_ip_address_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ip_address',
        ),
    ]
