# Generated by Django 4.2.1 on 2023-05-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_order_time_created_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_takeaway',
            field=models.IntegerField(choices=[(0, 'Here'), (1, 'Takeaway order')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Terminal')], default=0),
        ),
    ]
