# Generated by Django 4.2.1 on 2023-05-19 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0016_dish_created_at_alter_order_is_takeaway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
