# Generated by Django 4.2.1 on 2023-05-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0017_remove_dish_created_at_cart_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='dish',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
