# Generated by Django 4.2.1 on 2023-05-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0019_alter_order_options_alter_order_total_price_additive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additive',
            name='name',
        ),
        migrations.AddField(
            model_name='additive',
            name='name_en',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additive',
            name='name_kg',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additive',
            name='name_ru',
            field=models.CharField(default='Hello', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additive',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
