# Generated by Django 4.2.1 on 2023-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0020_remove_additive_name_additive_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='additives',
            field=models.ManyToManyField(to='cafe.additive'),
        ),
    ]
